### PR TITLE
Diversify codes; DRY the check

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by JBKahn** [comment]
Looks pretty good on my phone through vacation eyes. Away for the week but I'll take a look when I get back at what you have.

**Comment by mfalesni** [comment]
@JBKahn Thanks. The only functional difference is that I add a separate code for print function so I can enforce print functions in new code. Therefore I want to suppress the function issue and let the other two yell.

**Comment by jayvdb** [comment]
Code looks great.  Could you squash the three commits into a single commit.

What does DRY the check" mean in the summary of the first commit?  Is DRY an acronym?

**Comment by mfalesni** [comment]
Don't Repeat Yourself :) Yeah, once I get to the computer, I will.

**Comment by mfalesni** [comment]
@jayvdb Aaaand, it's done.

**Comment by JBKahn** [comment]
Can you make it `T003` instead of `2` because I use that in my debugger checker?

**Comment by mfalesni** [comment]
Sure.

**Comment by mfalesni** [comment]
@JBKahn Done.

**Comment by JBKahn** [comment]
pushed, version 2.0.2 should be up on pipy now.

**Comment by mfalesni** [comment]
Thanks, I have already installed this plugin in my flaker.

**Pull request merged**
